sudo: false
language: python
cache:
  directories:
- "$HOME/gcloud/"
env:
- PATH=$PATH:$HOME/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_71d955b72c3f_key -iv $encrypted_71d955b72c3f_iv -in gdglarioja-8eaa4e16b907.json.enc -out gdglarioja-8eaa4e16b907.json -d
- if [ ! -d $HOME/google-cloud-sdk ]; then  
    curl https://sdk.cloud.google.com | bash;
  fi
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- gcloud auth activate-service-account --key-file gdglarioja-8eaa4e16b907.json
install:
- gcloud config set compute/zone us-central1-b
- gcloud config set project gdglarioja-site
- gcloud -q components update
  
# [START travis_deploy]
#deploy:
#  provider: gae
#  skip_cleanup: true
#  keyfile: gdglarioja-8eaa4e16b907.json
#  project: gdglarioja-site
#  version: 2
#  default: true
#  on:
#    all_branches: true
# 
# [END travis_deploy]

script:
- gcloud -q preview app deploy app.yaml --set-default 
