deploy:
  provider: gae
  project: gdglarioja-site
before_install:
- openssl aes-256-cbc -K $encrypted_71d955b72c3f_key -iv $encrypted_71d955b72c3f_iv
  -in gdglarioja-8eaa4e16b907.json.enc -out gdglarioja-8eaa4e16b907.json -d
