before_install:
- openssl aes-256-cbc -K $encrypted_71d955b72c3f_key -iv $encrypted_71d955b72c3f_iv
  -in gdglarioja-8eaa4e16b907.json.enc -out gdglarioja-8eaa4e16b907.json -d
  
# [START travis_deploy]
deploy:
  provider: gae
  keyfile: gdglarioja-8eaa4e16b907.json
  project: gdglarioja-site
  version: 1
  default: true
  on:
    all_branches: true
 
# [END travis_deploy]
